name: Testing

on:
  push:
  pull_request:

jobs:
  testing:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        LUA: ['luajit-2.0.5', 'tarantool']
      fail-fast: false
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Tarantool
        if: matrix.LUA == 'tarantool'
        uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: '2.10'

      - name: Setup LuaJIT (${{ matrix.LUA }})
        if: matrix.LUA != 'tarantool'
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: ${{ matrix.LUA }}

      - name: Setup luarocks
        run: sudo apt install -y luarocks

      - name: Setup SQLite devepelopment package
        run: sudo apt install -y sqlite3 libsqlite3-dev

      - name: Setup dependencies
        run: make deps

      - run: echo $(luarocks path --lr-bin) >> $GITHUB_PATH

      - name: Run tests with Tarantool and send coverage to Coveralls.io
        if: matrix.LUA == 'tarantool'
        run: make coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEV: ON

      - name: Run tests with LuaJIT (${{ matrix.LUA }})
        if: matrix.LUA != 'tarantool'
        run: LUAJIT_BIN=$(pwd)/.lua/bin/luajit DEV=ON make test-luajit
